Folder structure and alpha backgrounds
tiaguinho/material-community-components pull request #165
Opened 2020-08-18 10:45 UTC by motabass

implements #163 and #164

2020-08-18 15:29 UTC, motabass commented
There is now also multiple fixes for alpha stuff in this PR, so wi would suggest to merge it before 7.2.0

2020-08-19 17:22 UTC, tiaguinho commented
Hi @motabass, can you do a rebase?

2020-08-20 09:28 UTC, motabass commented
This is done for the moment

2020-08-20 13:51 UTC, tiaguinho commented
@motabass this PR is ready for review?

2020-08-31 08:47 UTC, motabass commented
It is ready. But with secondary entry-points only.

2020-09-04 09:01 UTC, tiaguinho requested changes

2020-09-08 21:57 UTC, motabass commented on projects/material-community-components/README.md
> +To get more help on the Angular CLI use `ng help` or go check out the [Angular CLI README](https://github.com/angular/angular-cli/blob/master/README.md).
Hi @tiaguinho . I made the changes

2020-09-09 08:28 UTC, motabass commented
Due to having a Breaking Change, namely only secondary entry points, and many other UI fixes i would really go for version 8.0.0 or maybe even 9.0.0 for the next release. That could also indicate, that that the lib only works from angular 9 upwards (as stated here #168)

What do you think @tiaguinho?

2020-09-09 14:02 UTC, tiaguinho commented
I like your idea @motabass.
Let's call the next release 9.0.0.

2020-09-09 14:02 UTC, tiaguinho approved these changes

2020-09-09 14:02 UTC, merged